#pragma once

#define	PWM_TIM_PERDIO 			3000
#define	PWM_TIM_PERDIO_LIMIT 	2400

#define ADC_MEASURES_LEN (2048)
//#define ADC_HISTORY_LEN  64

#define FAKE_25_COLD_JUNGTION
#define FAKE_SUPPLY_VOLTAGE_OK
#define LEAVE_ONLY_IRON_MEAS

#define FLAWLESS_MEAS
